name: passage_flutter
description: Passkey Complete for Flutter - Go completely passwordless with a standalone auth solution in your Flutter app with Passage by 1Password
version: 1.0.0
homepage: https://docs.passage.id/complete

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.passage.passage_flutter
        pluginClass: PassageFlutterPlugin
      ios:
        pluginClass: PassageFlutterPlugin
      web:
        pluginClass: PassageFlutterWeb
        fileName: passage_flutter_web.dart
