name: passage_flutter
description: Native passkey authentication for your Flutter app
version: 0.4.0
homepage: https://github.com/passageidentity/passage-flutter

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.passage.passage_flutter
        pluginClass: PassageFlutterPlugin
      ios:
        pluginClass: PassageFlutterPlugin
      web:
        pluginClass: PassageFlutterWeb
        fileName: passage_flutter_web.dart
