name: iOS Integration Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./integrationtestapp

      - name: Install CocoaPods
        run: pod install --project-directory=ios
        working-directory: ./integrationtestapp

      - name: Install simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - name: List available simulators
        id: list_simulators
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices | grep -E 'iPhone [0-9]+ \(.*\)' | grep -Eo '[0-9A-F-]{36}' | head -n 1)
          echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

      - name: Run iOS tests
        run: flutter test integration_test/*.dart -d $SIMULATOR_ID --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }}
        working-directory: ./integrationtestapp
        env:
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
