name: iOS Integration Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./integrationtestapp

      - name: Install CocoaPods
        run: pod install --project-directory=ios
        working-directory: ./integrationtestapp

      - name: List available simulators
        run: xcrun simctl list devices
        id: list_simulators

      - name: Extract device ID
        run: echo "::set-output name=device_id::$(xcrun simctl list devices | grep -m 1 '(Booted)' | awk '{print $2}')"
        id: extract_device_id

      - name: Launch iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          sudo xcodebuild -runFirstLaunch
          xcrun simctl boot ${{ steps.extract_device_id.outputs.device_id }}
          xcrun simctl bootstatus ${{ steps.extract_device_id.outputs.device_id }}
        env:
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

      - name: Run iOS tests
        run: flutter test integration_test/*.dart -d ${{ steps.extract_device_id.outputs.device_id }} --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }}
        working-directory: ./integrationtestapp
        env:
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
