name: Web Integration Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd proxy-server
          npm install
          cd ../..
          flutter pub get
        working-directory: ./integrationtestapp

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          sudo apt-get install -y google-chrome-stable=126.0.6478.62-1
        shell: bash

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y xvfb
          wget -N https://chromedriver.storage.googleapis.com/125.0.6422.141/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Start Proxy Server
        run: |
          nohup node integrationtestapp/proxy-server/proxy_server.js &
          sleep 5
        env:
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

      - name: Run Web tests with XVFB
        run: |
          nohup xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" flutter drive --driver=test_driver/integration_test.dart --target=integration_test/change_user_info_test.dart -d chrome --web-port 4200 --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }}
        working-directory: ./integrationtestapp
        env:
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
